<?php
return array (
  'mgtv' => 
  array (
    'status' => '1',
    'from' => 'mgtv',
    'show' => '芒果',
    'des' => '支持手机电脑在线播放',
    'ps' => '1',
    'parse' => '//cdn.zyc888.top/?url=',
    'parse2' => 'https://m3u8..tv.janan.net/json.php?url=',
    'sort' => '1006',
    'tip' => '无需安装任何插件',
    'id' => 'mgtv',
  ),
  'pptv' => 
  array (
    'status' => '1',
    'from' => 'pptv',
    'show' => 'PPTV',
    'des' => '支持手机电脑在线播放',
    'ps' => '1',
    'parse' => '//cdn.zyc888.top/?url=',
    'parse2' => 'https://vip..parwix.com:4433/analysis/json/?uid=641&my=chlnptwxDEFJKSW079&url=',
    'sort' => '1005',
    'tip' => '无需安装任何插件',
    'id' => 'pptv',
  ),
  'letv' => 
  array (
    'status' => '1',
    'from' => 'letv',
    'show' => '乐视',
    'des' => '支持手机电脑在线播放',
    'ps' => '1',
    'parse' => '//cdn.zyc888.top/?url=',
    'parse2' => 'https://vip..parwix.com:4433/analysis/json/?uid=641&my=chlnptwxDEFJKSW079&url=',
    'sort' => '1004',
    'tip' => '无需安装任何插件',
    'id' => 'letv',
  ),
  'sohu' => 
  array (
    'status' => '1',
    'from' => 'sohu',
    'show' => '搜狐',
    'des' => '支持手机电脑在线播放',
    'ps' => '1',
    'parse' => '//cdn.zyc888.top/?url=',
    'parse2' => 'https://vip..jhys.top/analysis/json/?uid=350&my=adijmtwyzILOQST125&url=',
    'sort' => '1003',
    'tip' => '无需安装任何插件',
    'id' => 'sohu',
  ),
  'youku' => 
  array (
    'status' => '1',
    'from' => 'youku',
    'show' => '优酷',
    'des' => '支持手机电脑在线播放',
    'ps' => '1',
    'parse' => '//cdn.zyc888.top/?url=',
    'parse2' => 'https://svip.4kya.com/api/?key=D2YUv19tzU7uNnYpL9&url=',
    'sort' => '1001',
    'tip' => '无需安装任何插件',
    'id' => 'youku',
  ),
  'qq' => 
  array (
    'status' => '1',
    'from' => 'qq',
    'show' => '腾讯',
    'des' => '支持手机电脑在线播放',
    'ps' => '1',
    'parse' => '//cdn.zyc888.top/?url=',
    'parse2' => 'https://m3u8..tv.janan.net/json.php?url=',
    'sort' => '1000',
    'tip' => '无需安装任何插件',
    'id' => 'qq',
  ),
  'qiyi' => 
  array (
    'status' => '1',
    'from' => 'qiyi',
    'show' => '奇艺',
    'des' => 'qiyi.com',
    'ps' => '1',
    'parse' => '//cdn.zyc888.top/?url=',
    'parse2' => 'https://m3u8..tv.janan.net/json.php?url=',
    'sort' => '999',
    'tip' => '无需安装任何插件',
    'id' => 'qiyi',
  ),
);